// ─────────────────────────────────────────────────────────────────────────────
// Exhaustive MIME map — 250+ types, grouped by category.
// Fallback: "application/octet-stream" (forces download for unknown types).
// ─────────────────────────────────────────────────────────────────────────────
export const MIME_MAP: Record<string, string> = {
    // ── Web ──────────────────────────────────────────────────────────────────
    ".html": "text/html; charset=utf-8",
    ".htm": "text/html; charset=utf-8",
    ".xhtml": "application/xhtml+xml",
    ".css": "text/css; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".mjs": "application/javascript; charset=utf-8",
    ".cjs": "application/javascript; charset=utf-8",
    ".jsx": "text/jsx; charset=utf-8",
    ".tsx": "text/tsx; charset=utf-8",
    ".map": "application/json",
    ".wasm": "application/wasm",
    ".wat": "text/plain; charset=utf-8",
    ".manifest": "application/manifest+json",
    ".webmanifest": "application/manifest+json",
    ".htaccess": "text/plain; charset=utf-8",
    ".htpasswd": "text/plain; charset=utf-8",
    ".sse": "text/event-stream; charset=utf-8",

    // ── Data ─────────────────────────────────────────────────────────────────
    ".json": "application/json; charset=utf-8",
    ".jsonl": "application/x-ndjson; charset=utf-8",
    ".ndjson": "application/x-ndjson; charset=utf-8",
    ".json5": "application/json5; charset=utf-8",
    ".jsonc": "application/json; charset=utf-8",
    ".xml": "application/xml; charset=utf-8",
    ".xsl": "application/xslt+xml; charset=utf-8",
    ".xslt": "application/xslt+xml; charset=utf-8",
    ".xsd": "application/xml; charset=utf-8",
    ".dtd": "application/xml-dtd; charset=utf-8",
    ".yaml": "application/yaml; charset=utf-8",
    ".yml": "application/yaml; charset=utf-8",
    ".toml": "application/toml; charset=utf-8",
    ".csv": "text/csv; charset=utf-8",
    ".tsv": "text/tab-separated-values; charset=utf-8",
    ".graphql": "application/graphql; charset=utf-8",
    ".gql": "application/graphql; charset=utf-8",
    ".proto": "text/plain; charset=utf-8",
    ".parquet": "application/vnd.apache.parquet",
    ".avro": "application/vnd.apache.avro",
    ".arrow": "application/vnd.apache.arrow.file",
    ".feather": "application/vnd.apache.arrow.file",
    ".msgpack": "application/msgpack",
    ".cbor": "application/cbor",
    ".ion": "application/ion",

    // ── Text / Markup ─────────────────────────────────────────────────────────
    ".txt": "text/plain; charset=utf-8",
    ".md": "text/markdown; charset=utf-8",
    ".markdown": "text/markdown; charset=utf-8",
    ".mdx": "text/markdown; charset=utf-8",
    ".rst": "text/x-rst; charset=utf-8",
    ".asciidoc": "text/asciidoc; charset=utf-8",
    ".adoc": "text/asciidoc; charset=utf-8",
    ".textile": "text/x-textile; charset=utf-8",
    ".org": "text/x-org; charset=utf-8",
    ".log": "text/plain; charset=utf-8",
    ".ini": "text/plain; charset=utf-8",
    ".cfg": "text/plain; charset=utf-8",
    ".conf": "text/plain; charset=utf-8",
    ".env": "text/plain; charset=utf-8",
    ".lock": "text/plain; charset=utf-8",
    ".diff": "text/x-diff; charset=utf-8",
    ".patch": "text/x-diff; charset=utf-8",

    // ── Shell / Scripts ───────────────────────────────────────────────────────
    ".sh": "text/x-shellscript; charset=utf-8",
    ".bash": "text/x-shellscript; charset=utf-8",
    ".zsh": "text/x-shellscript; charset=utf-8",
    ".fish": "text/x-shellscript; charset=utf-8",
    ".bat": "text/plain; charset=utf-8",
    ".cmd": "text/plain; charset=utf-8",
    ".ps1": "text/plain; charset=utf-8",
    ".psm1": "text/plain; charset=utf-8",
    ".psd1": "text/plain; charset=utf-8",

    // ── Calendars / Contacts / Subtitles ─────────────────────────────────────
    ".ics": "text/calendar; charset=utf-8",
    ".vcf": "text/vcard; charset=utf-8",
    ".vcard": "text/vcard; charset=utf-8",
    ".srt": "text/plain; charset=utf-8",
    ".vtt": "text/vtt; charset=utf-8",
    ".ass": "text/plain; charset=utf-8",
    ".sub": "text/plain; charset=utf-8",
    ".lrc": "text/plain; charset=utf-8",

    // ── Images ───────────────────────────────────────────────────────────────
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".jfif": "image/jpeg",
    ".pjpeg": "image/jpeg",
    ".pjp": "image/jpeg",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".svg": "image/svg+xml",
    ".svgz": "image/svg+xml",
    ".ico": "image/x-icon",
    ".cur": "image/vnd.microsoft.icon",
    ".bmp": "image/bmp",
    ".tiff": "image/tiff",
    ".tif": "image/tiff",
    ".avif": "image/avif",
    ".apng": "image/apng",
    ".heic": "image/heic",
    ".heif": "image/heif",
    ".jxl": "image/jxl",
    ".jp2": "image/jp2",
    ".jpx": "image/jpx",
    ".j2k": "image/j2c",
    ".qoi": "image/x-qoi",
    ".wbmp": "image/vnd.wap.wbmp",
    ".xbm": "image/x-xbitmap",
    ".xpm": "image/x-xpixmap",
    // RAW camera formats
    ".raw": "image/x-raw",
    ".arw": "image/x-sony-arw",
    ".cr2": "image/x-canon-cr2",
    ".cr3": "image/x-canon-cr3",
    ".nef": "image/x-nikon-nef",
    ".orf": "image/x-olympus-orf",
    ".dng": "image/x-adobe-dng",
    ".rw2": "image/x-panasonic-rw2",
    ".raf": "image/x-fuji-raf",
    // HDR / compositing
    ".exr": "image/x-exr",
    ".hdr": "image/vnd.radiance",
    ".rgbe": "image/vnd.radiance",

    // ── Fonts ────────────────────────────────────────────────────────────────
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".ttf": "font/ttf",
    ".otf": "font/otf",
    ".sfnt": "font/sfnt",
    ".eot": "application/vnd.ms-fontobject",
    ".afm": "application/x-font-afm",
    ".pfb": "application/x-font-type1",
    ".pfm": "application/x-font-type1",

    // ── Audio ─────────────────────────────────────────────────────────────────
    ".mp3": "audio/mpeg",
    ".mpeg": "audio/mpeg",
    ".ogg": "audio/ogg",
    ".oga": "audio/ogg",
    ".opus": "audio/ogg; codecs=opus",
    ".wav": "audio/wav",
    ".aac": "audio/aac",
    ".m4a": "audio/mp4",
    ".flac": "audio/flac",
    ".webma": "audio/webm",
    ".wma": "audio/x-ms-wma",
    ".mid": "audio/midi",
    ".midi": "audio/midi",
    ".aiff": "audio/aiff",
    ".aif": "audio/aiff",
    ".amr": "audio/amr",
    ".au": "audio/basic",
    ".ra": "audio/x-realaudio",
    ".3ga": "audio/3gpp",
    ".caf": "audio/x-caf",
    ".dsf": "audio/x-dsf",
    ".dff": "audio/x-dff",

    // ── Video ─────────────────────────────────────────────────────────────────
    ".mp4": "video/mp4",
    ".m4v": "video/mp4",
    ".f4v": "video/mp4",
    ".webm": "video/webm",
    ".ogv": "video/ogg",
    ".avi": "video/x-msvideo",
    ".mov": "video/quicktime",
    ".qt": "video/quicktime",
    ".mkv": "video/x-matroska",
    ".flv": "video/x-flv",
    ".wmv": "video/x-ms-wmv",
    ".asf": "video/x-ms-asf",
    ".3gp": "video/3gpp",
    ".3g2": "video/3gpp2",
    ".m3u8": "application/vnd.apple.mpegurl",
    ".m3u": "audio/x-mpegurl",
    ".mpd": "application/dash+xml",
    ".ts": "video/mp2t",
    ".mts": "video/mp2t",
    ".m2ts": "video/mp2t",
    ".vob": "video/dvd",
    ".mxf": "application/mxf",
    ".hevc": "video/hevc",
    ".divx": "video/x-divx",

    // ── Documents ────────────────────────────────────────────────────────────
    ".pdf": "application/pdf",
    // Microsoft Word
    ".doc": "application/msword",
    ".dot": "application/msword",
    ".docx":
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".dotx":
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    ".docm": "application/vnd.ms-word.document.macroEnabled.12",
    // Microsoft Excel
    ".xls": "application/vnd.ms-excel",
    ".xlt": "application/vnd.ms-excel",
    ".xlsx":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xltx":
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    ".xlsm": "application/vnd.ms-excel.sheet.macroEnabled.12",
    ".xlsb": "application/vnd.ms-excel.sheet.binary.macroEnabled.12",
    // Microsoft PowerPoint
    ".ppt": "application/vnd.ms-powerpoint",
    ".pot": "application/vnd.ms-powerpoint",
    ".pptx":
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".potx":
        "application/vnd.openxmlformats-officedocument.presentationml.template",
    ".ppsx":
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    ".pptm": "application/vnd.ms-powerpoint.presentation.macroEnabled.12",
    // OpenDocument
    ".odt": "application/vnd.oasis.opendocument.text",
    ".ott": "application/vnd.oasis.opendocument.text-template",
    ".ods": "application/vnd.oasis.opendocument.spreadsheet",
    ".odp": "application/vnd.oasis.opendocument.presentation",
    ".odg": "application/vnd.oasis.opendocument.graphics",
    ".odf": "application/vnd.oasis.opendocument.formula",
    // Apple iWork
    ".pages": "application/vnd.apple.pages",
    ".numbers": "application/vnd.apple.numbers",
    ".keynote": "application/vnd.apple.keynote",
    // Other documents
    ".rtf": "application/rtf",
    ".abw": "application/x-abiword",
    ".epub": "application/epub+zip",
    ".mobi": "application/x-mobipocket-ebook",
    ".azw": "application/vnd.amazon.ebook",
    ".azw3": "application/vnd.amazon.ebook",
    ".djvu": "image/vnd.djvu",
    ".djv": "image/vnd.djvu",
    ".xps": "application/vnd.ms-xpsdocument",
    ".oxps": "application/oxps",
    ".tex": "application/x-tex; charset=utf-8",
    ".latex": "application/x-latex; charset=utf-8",
    ".bib": "text/x-bibtex; charset=utf-8",

    // ── Archives ─────────────────────────────────────────────────────────────
    ".zip": "application/zip",
    ".gz": "application/gzip",
    ".tgz": "application/gzip",
    ".bz2": "application/x-bzip2",
    ".tbz2": "application/x-bzip2",
    ".tar": "application/x-tar",
    ".rar": "application/vnd.rar",
    ".7z": "application/x-7z-compressed",
    ".xz": "application/x-xz",
    ".txz": "application/x-xz",
    ".zst": "application/zstd",
    ".br": "application/x-brotli",
    ".lz4": "application/x-lz4",
    ".lz": "application/x-lzip",
    ".lzma": "application/x-lzma",
    ".cab": "application/vnd.ms-cab-compressed",
    ".iso": "application/x-iso9660-image",
    ".img": "application/octet-stream",
    ".jar": "application/java-archive",
    ".war": "application/java-archive",
    ".ear": "application/java-archive",
    ".whl": "application/zip",
    ".egg": "application/zip",

    // ── Code / Dev ───────────────────────────────────────────────────────────
    // TypeScript (note: .ts is video/mp2t in Video section above — avoid collision
    //   by serving .ts files differently depending on context; this entry covers
    //   source-code usage when served directly as a dev asset)
    // Python
    ".py": "text/x-python; charset=utf-8",
    ".pyi": "text/x-python; charset=utf-8",
    ".pyc": "application/octet-stream",
    // Ruby
    ".rb": "text/x-ruby; charset=utf-8",
    ".gemspec": "text/x-ruby; charset=utf-8",
    // PHP
    ".php": "text/x-php; charset=utf-8",
    ".php3": "text/x-php; charset=utf-8",
    ".php4": "text/x-php; charset=utf-8",
    // Java / JVM
    ".java": "text/x-java-source; charset=utf-8",
    ".class": "application/java-vm",
    ".groovy": "text/x-groovy; charset=utf-8",
    ".gradle": "text/x-groovy; charset=utf-8",
    ".scala": "text/x-scala; charset=utf-8",
    ".kt": "text/x-kotlin; charset=utf-8",
    ".kts": "text/x-kotlin; charset=utf-8",
    // C / C++
    ".c": "text/x-csrc; charset=utf-8",
    ".h": "text/x-chdr; charset=utf-8",
    ".cpp": "text/x-c++src; charset=utf-8",
    ".cc": "text/x-c++src; charset=utf-8",
    ".cxx": "text/x-c++src; charset=utf-8",
    ".hpp": "text/x-c++hdr; charset=utf-8",
    ".hxx": "text/x-c++hdr; charset=utf-8",
    // .NET
    ".cs": "text/x-csharp; charset=utf-8",
    ".fs": "text/x-fsharp; charset=utf-8",
    ".fsx": "text/x-fsharp; charset=utf-8",
    ".vb": "text/x-vb; charset=utf-8",
    // Systems
    ".rs": "text/x-rust; charset=utf-8",
    ".go": "text/x-go; charset=utf-8",
    ".swift": "text/x-swift; charset=utf-8",
    // Scripting / dynamic
    ".dart": "text/x-dart; charset=utf-8",
    ".lua": "text/x-lua; charset=utf-8",
    ".pl": "text/x-perl; charset=utf-8",
    ".pm": "text/x-perl; charset=utf-8",
    ".r": "text/x-r; charset=utf-8",
    ".rmd": "text/x-r; charset=utf-8",
    ".jl": "text/x-julia; charset=utf-8",
    // Functional
    ".hs": "text/x-haskell; charset=utf-8",
    ".lhs": "text/x-haskell; charset=utf-8",
    ".ml": "text/x-ocaml; charset=utf-8",
    ".mli": "text/x-ocaml; charset=utf-8",
    ".clj": "text/x-clojure; charset=utf-8",
    ".cljs": "text/x-clojure; charset=utf-8",
    ".ex": "text/x-elixir; charset=utf-8",
    ".exs": "text/x-elixir; charset=utf-8",
    ".erl": "text/x-erlang; charset=utf-8",
    ".hrl": "text/x-erlang; charset=utf-8",
    // Data / DB
    ".sql": "application/sql; charset=utf-8",
    ".sqlite": "application/vnd.sqlite3",
    ".db": "application/vnd.sqlite3",
    // Build / Infra / Config
    ".tf": "text/x-terraform; charset=utf-8",
    ".tfvars": "text/x-terraform; charset=utf-8",
    ".bicep": "text/plain; charset=utf-8",
    ".cmake": "text/x-cmake; charset=utf-8",
    ".make": "text/x-makefile; charset=utf-8",
    ".mk": "text/x-makefile; charset=utf-8",
    ".dockerfile": "text/plain; charset=utf-8",
    ".nix": "text/x-nix; charset=utf-8",
    ".vim": "text/x-vim; charset=utf-8",

    // ── Binaries / Executables ───────────────────────────────────────────────
    // Windows
    ".exe": "application/vnd.microsoft.portable-executable",
    ".dll": "application/vnd.microsoft.portable-executable",
    ".msi": "application/x-msdownload",
    // Unix / macOS
    ".so": "application/octet-stream",
    ".dylib": "application/octet-stream",
    ".dmg": "application/x-apple-diskimage",
    ".pkg": "application/x-newton-compatible-pkg",
    // Linux packages
    ".deb": "application/vnd.debian.binary-package",
    ".rpm": "application/x-rpm",
    ".snap": "application/vnd.snap",
    ".flatpak": "application/vnd.flatpak",
    ".appimage": "application/octet-stream",
    // Mobile
    ".apk": "application/vnd.android.package-archive",
    ".aab": "application/vnd.android.package-archive",
    ".ipa": "application/octet-stream",
    // Browser extensions
    ".xpi": "application/x-xpinstall",
    ".crx": "application/x-chrome-extension",

    // ── 3D / CAD / Design ────────────────────────────────────────────────────
    // 3D formats
    ".glb": "model/gltf-binary",
    ".gltf": "model/gltf+json",
    ".obj": "model/obj",
    ".mtl": "model/mtl",
    ".stl": "model/stl",
    ".ply": "model/ply",
    ".fbx": "application/octet-stream",
    ".dae": "model/vnd.collada+xml",
    ".3ds": "image/x-3ds",
    ".usdz": "model/vnd.usdz+zip",
    ".usd": "model/vnd.usd",
    // CAD exchange
    ".step": "application/step",
    ".stp": "application/step",
    ".iges": "model/iges",
    ".igs": "model/iges",
    // Raster design
    ".psd": "image/vnd.adobe.photoshop",
    ".psb": "image/vnd.adobe.photoshop",
    ".xcf": "image/x-xcf",
    // Vector / print
    ".ai": "application/postscript",
    ".eps": "application/postscript",
    ".ps": "application/postscript",
    ".indd": "application/x-indesign",
    // UI / prototyping
    ".fig": "application/octet-stream",
    ".sketch": "application/octet-stream",
    ".afdesign": "application/octet-stream",
    ".afphoto": "application/octet-stream",

    // ── Certificates / Security ──────────────────────────────────────────────
    ".pem": "application/x-pem-file",
    ".crt": "application/x-x509-ca-cert",
    ".cer": "application/x-x509-ca-cert",
    ".der": "application/x-x509-ca-cert",
    ".key": "application/x-pem-file",
    ".csr": "application/pkcs10",
    ".p7b": "application/x-pkcs7-certificates",
    ".p7c": "application/pkcs7-mime",
    ".p12": "application/x-pkcs12",
    ".pfx": "application/x-pkcs12",
    ".jks": "application/octet-stream",
    ".gpg": "application/pgp-encrypted",
    ".asc": "application/pgp-signature",
    ".sig": "application/pgp-signature",

    // ── Geospatial ───────────────────────────────────────────────────────────
    ".geojson": "application/geo+json; charset=utf-8",
    ".topojson": "application/json; charset=utf-8",
    ".kml": "application/vnd.google-earth.kml+xml",
    ".kmz": "application/vnd.google-earth.kmz",
    ".gpx": "application/gpx+xml",
    ".shp": "application/octet-stream",
    ".shx": "application/octet-stream",
    ".dbf": "application/octet-stream",
    ".mbtiles": "application/vnd.mapbox-vector-tile",
    ".pbf": "application/vnd.mapbox-vector-tile",

    // ── E-mail ───────────────────────────────────────────────────────────────
    ".eml": "message/rfc822",
    ".msg": "application/vnd.ms-outlook",
    ".mbox": "application/mbox",
    ".mime": "message/rfc822",
};
